name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        # Build each combination of OS and release/debug variants
        os: [ "ubuntu-latest", "ubuntu-22.04", "ubuntu-24.04" ]

    runs-on: ${{ os }}
    
    steps:
    - uses: actions/checkout@v3

    - name: Compile
      run: clang++ test.cpp -std=gnu++20

  build-workaround:
    strategy:
      matrix:
        # Build each combination of OS and release/debug variants
        os: [ "ubuntu-latest", "ubuntu-22.04", "ubuntu-24.04" ]

    runs-on: ${{ os }}

    steps:
    - uses: actions/checkout@v3

    - uses: ./

    - name: Compile
      run: clang++ test.cpp -std=gnu++20
